name: Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install format dependencies
        run: |
          brew install clang-format
          pip install cmake_format pyyaml

      - name: configure
        run: cmake -Htest -Bbuild

      - name: check style
        run: cmake --build build --target check-format
